feat: bio use v-html
storipress/karbon pull request #250
Opened 2023-09-11 08:16 UTC by ches4117

2023-09-11 09:26 UTC, DanSnow requested changes

2023-09-11 09:26 UTC, DanSnow commented on packages/karbon/src/module.ts
> +      },
missing server plugin

2023-09-11 09:26 UTC, ches4117 commented on packages/karbon/src/module.ts
> +      },
好

2023-09-11 09:27 UTC, ches4117 commented on packages/karbon/src/module.ts
> +      },
fixed

2023-09-11 09:29 UTC, ches4117 commented on packages/karbon/src/module.ts
> +          resolvedSEO.map((config) => {
咦, 又重新排版了

2023-09-11 09:32 UTC, ches4117 commented on packages/karbon/src/module.ts
> +          resolvedSEO.map((config) => {
fixed

2023-09-11 10:14 UTC, DanSnow requested changes
Author page doesn't have `bioHTML` 
![image](https://github.com/storipress/karbon/assets/5575082/8033eebd-5acf-4df6-b844-d77b26944009)

2023-09-12 03:39 UTC, DanSnow approved these changes

2023-09-12 03:39 UTC, merged