fix: seo meta add author description
storipress/karbon pull request #256
Opened 2023-09-13 06:52 UTC by SidStraw

https://storipress-media.atlassian.net/browse/SPMVP-6421

驗證：
開啟 author page 檢查 meta
![image](https://github.com/storipress/karbon/assets/37400982/eac4ec6d-b20e-438d-9dbb-28917bfbae36)

2023-09-14 04:41 UTC, DanSnow requested changes
可以再加個 desk page 的 title 嗎？

2023-09-14 04:41 UTC, DanSnow commented on packages/karbon/src/runtime/composables/seo.ts
> +  return withTrailingSlash(resolveURL(siteUrl, url))
這邊要用 `withoutTrailingSlash`

2023-09-14 04:41 UTC, DanSnow commented on packages/karbon/src/runtime/composables/seo.ts
> +  const typeName: ResourceType = input.__typename || '_'
🤔  typename 可能不是那麼可靠的資料來源，有辦法用其它方式傳進來嗎？

2023-09-18 07:12 UTC, DanSnow requested changes
author 的 bio 之後會支援使用 rich text ，這邊可以幫忙用 `useArticleFilter` 回傳的 function 來過濾 html tag 嗎？
![image](https://github.com/storipress/karbon/assets/5575082/563a899c-08b8-4532-a73b-c828506ae7e6)

2023-09-20 15:21 UTC, SidStraw commented
重要改動：
1. Rebase
2. 修復 `Unhead is missing Vue context` 在 `composables/seo.ts` 與 `plugins/html-attribute.ts` 中的問題[SPMVP-6535 - Fix Unhead is missing Vue context, falling back to shared context.](https://storipress-media.atlassian.net/browse/SPMVP-6535)
3. 這個 PR 的 commit 已經剪入目前分支，並處理過衝突後測試 https://github.com/storipress/karbon/pull/267
4. Fix change request.

2023-09-21 05:23 UTC, DanSnow approved these changes

2023-09-21 05:24 UTC, merged