feat: Add Noindex to authors pages with no articles
storipress/karbon pull request #270
Opened 2023-09-21 03:44 UTC by SidStraw

https://storipress-media.atlassian.net/browse/SPMVP-6419

> 沒有文章的作者
<img width="733" alt="image" src="https://github.com/storipress/karbon/assets/37400982/9c7a93ae-a323-42f9-bf6a-1aede6f41f3b">

> 有文章的作者
<img width="733" alt="image" src="https://github.com/storipress/karbon/assets/37400982/7e1c3d3e-1f4f-4d8b-9ffb-c25957c6b650">

2023-09-21 08:23 UTC, DanSnow requested changes

2023-09-21 08:23 UTC, DanSnow commented on packages/karbon/src/runtime/composables/page-meta.ts
> +      useSeoMeta({ robots: 'noindex' })
missing import for `useSeoMeta`

2023-09-23 03:56 UTC, DanSnow requested changes

2023-09-23 03:56 UTC, DanSnow commented on packages/karbon/src/runtime/composables/page-meta.ts
> +    const { preload } = useArticleLoader({
由於 `useArticleLoader` 內部是有狀態的，會避免重覆使用文章，這個會影響到 author page 上的文章填充，有辦法換其它方式嗎？

2023-10-02 06:09 UTC, SidStraw commented on packages/karbon/src/runtime/composables/page-meta.ts
> +    const { preload } = useArticleLoader({
已上傳更新改動

2023-10-03 03:39 UTC, DanSnow approved these changes

2023-10-03 03:39 UTC, merged