feat: [SPMVP -6521] use typesense to fetch article list in karbon to reduce api server load
storipress/karbon pull request #281
Opened 2023-10-06 23:37 UTC by SidStraw

- Verify that the article list and page display are normal.
- Confirm that `/sitemap.xml` is functioning correctly.
- Ensure that `/atom.xml` is working as expected.
- Check the effectiveness of the `filter_by` feature.

2023-10-09 13:09 UTC, DanSnow requested changes

2023-10-09 13:09 UTC, DanSnow commented on packages/karbon/src/runtime/api/sitemap.ts
> +          const documents = typesenseClient?.collections('articles').documents()
目前不確定為什麼，在測試 sitemap 與 feed 時速度比起 front page 要來的慢很多，有辦法確定原因嗎？

2023-10-09 13:09 UTC, DanSnow commented on packages/karbon/src/runtime/composables/typesense-client.ts
> +export function getSearchQuery(page = 1, filter: TypesenseFilter = {}) {
👍 這樣整理出來我覺得是很好的設計

2023-10-09 13:09 UTC, DanSnow commented on packages/karbon/src/runtime/composables/typesense-client.ts
> +    preset: `list-articles-${page}`,
💭  這個 preset 好像用法不太對，這邊應該不需要 https://typesense.org/docs/0.25.1/api/search.html#presets

2023-10-12 01:37 UTC, SidStraw commented on packages/karbon/src/runtime/composables/typesense-client.ts
> +    preset: `list-articles-${page}`,
已經修正，因為型別錯誤誤以為這是必要屬性，但原因是我有漏掉其他必要屬性才會顯示缺少 preset

2023-10-12 01:38 UTC, SidStraw commented on packages/karbon/src/runtime/api/sitemap.ts
> +          const documents = typesenseClient?.collections('articles').documents()
調整作法為使用 payload 作為資料來源

2023-10-12 07:39 UTC, DanSnow requested changes
change req delivier via slack

2023-10-17 06:20 UTC, SidStraw commented
透過其他專案驗證：

![image](https://github.com/storipress/karbon/assets/37400982/e4f4d06b-88c4-45e1-a445-8e9ee90fb0b9)

2023-10-17 07:43 UTC, DanSnow approved these changes
🎉

2023-10-17 07:43 UTC, merged